name: CI
on:
  push:
  schedule:
    - cron: '0 3 * * SUN'

jobs:
  CI-Complete:
    needs: Build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: success
      - shell: bash
        run: '[ -f ok ]'
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Clone
        shell: bash
        run: git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY $GITHUB_WORKSPACE
      - name: Checkout
        shell: bash
        run: git checkout "$(echo ${{ github.event.ref }} | sed s#refs/heads/## | sed s#refs/tags##)"
      - name: Update APT
        run: sudo apt-get -y update
      - name: Install TeXLive
        run: while read package; do sudo apt-get install -y $package; done < .github/ubuntu-packages
      - name: Compile LaTeX
        shell: bash
        run: ./gradlew buildLatex
      - name: Compute Version
        run: |
          VERSION=$(git describe --tags --exact-match HEAD || \
            git describe || \
            echo "0.1.0-$(git log -n1 --date=format:'%Y-%m-%dT%H%M%S' --format=%cd)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body_path: CHANGELOG.md
          files: *.pdf
          fail_on_unmatched_files: true
      - shell: bash
        run: touch ok
      - uses: actions/upload-artifact@v2
        with:
          name: success
          path: ok
  Automerge:
    needs: CI-Complete
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: automerge
        uses: "DanySK/yaagha@master"
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOMERGE_TOKEN }}"
          MERGE_FORKS: "false"
          MERGE_LABELS: "version-upgrade"
          MERGE_METHOD: "rebase"
          CLOSE_ON_CONFLICT: "true"
          DELETE_BRANCH_ON_CLOSE: "true"
          GIT_USER_NAME: "Danilo Pianini"
          GIT_USER_EMAIL: "danilo.pianini@gmail.com"